# Generated by Django 4.2.1 on 2023-05-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, unique=True)),
                ('short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SubMedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('med_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservice.medservice')),
            ],
        ),
        migrations.AddField(
            model_name='medservice',
            name='med_service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medservice.medservicecategory'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('price', models.PositiveIntegerField()),
                ('interesting_fact', models.TextField(blank=True, max_length=1000)),
                ('preparation', models.ManyToManyField(to='medservice.preparation')),
            ],
        ),
        migrations.CreateModel(
            name='SubMedServiceCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medservice.card')),
                ('sub_med_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medservice.submedservice')),
            ],
            bases=('medservice.card',),
        ),
        migrations.CreateModel(
            name='MedServiceCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medservice.card')),
                ('med_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medservice.medservice')),
            ],
            bases=('medservice.card',),
        ),
    ]
