# Generated by Django 4.2.1 on 2023-05-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('is_available_indoor', models.BooleanField(default=True)),
                ('is_available_homevisit', models.BooleanField(default=False)),
                ('is_available_video', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='preparation',
            name='name',
            field=models.TextField(max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=50)),
                ('education_and_degree', models.TextField(max_length=2000)),
                ('date_med_practice_started', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('med_specialty', models.ManyToManyField(to='medservice.medspecialty')),
            ],
        ),
    ]
