# Generated by Django 4.2.1 on 2023-05-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0002_medspecialty_alter_preparation_name_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='medspecialty',
            old_name='is_available_homevisit',
            new_name='is_available_home_visit',
        ),
    ]
