# Generated by Django 4.2.1 on 2023-05-28 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medservice', '0003_rename_is_available_doctor_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medspecialty',
            name='short_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
